export const USER_STATE = {
  IDLE: 'IDLE',
  AWAITING_API_URL: 'AWAITING_API_URL',
  AWAITING_CUSTOM_DOMAIN: 'AWAITING_CUSTOM_DOMAIN',
  RENAMING_KEY_PREFIX: 'RENAMING_KEY:',
  MIGRATE_AWAIT_OLD_HOST: 'MIGRATE_AWAIT_OLD_HOST',
  MIGRATE_AWAIT_OLD_USER: 'MIGRATE_AWAIT_OLD_USER',
  MIGRATE_AWAIT_OLD_PASSWORD: 'MIGRATE_AWAIT_OLD_PASSWORD',
  MIGRATE_AWAIT_NEW_HOST: 'MIGRATE_AWAIT_NEW_HOST',
  MIGRATE_AWAIT_NEW_USER: 'MIGRATE_AWAIT_NEW_USER',
  MIGRATE_AWAIT_NEW_PASSWORD: 'MIGRATE_AWAIT_NEW_PASSWORD',
  MIGRATE_PENDING_START: 'MIGRATE_PENDING_START',
} as const;

export type UserStateValue = string;
